### ISSUE TITLE
AnimUtils is package-private

### ISSUE THREAD

**Issue by wasdennnoch** [Commit451/MorphTransitions#1]
Hi, the AnimUtils class has no access modifier (this is only available to this package), but in Plaid it's public and I need access to the TransitionListenerAdapter (that is what it is for, public usage).

**Comment by Jawnnypoo** [comment]
Hey,

AnimUtils is package private because it is an implementation detail that the end user does not need to know about. It is copied from Plaid to allow for the two MorphTransitions that this library seeks to provide easy access to. 

If you want something from AnimUtils, you should just go copy the class from Plaid, since this lib does not use the TransitionListenerAdapter anyhow.
